name: SQL Autograding

on:
  push:
  workflow_dispatch:

jobs:
  grade:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0

        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mysql

        ports:
          - 3306:3306

        options: >-
          --health-cmd="mysqladmin ping -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=20

    steps:

      - uses: actions/checkout@v4

      - name: Install MySQL Client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h127.0.0.1 -uroot -proot --silent
          do
            sleep 3
          done

      - name: Show Repository Files
        run: ls -l

      - name: Show Student SQL
        run: cat student_solution.sql

      - name: Make test executable
        run: chmod +x test.sh

      - name: Run Tests
        run: ./test.sh
